{config, lib, pkgs, ... }:
{
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    killall
    brightnessctl
    playerctl
    grim
    wl-clipboard
    swww
    rofi-wayland
    dunst
    cool-retro-term
    lm_sensors
    
    zsh
    tmux
    kitty
    ghostty
    obsidian
    

    #server thingy
    samba

    obs-studio
    flameshot
    peaclock
    vscodium
    neovim
    pavucontrol
    imv
    nwg-look
    mpv
    zathura
    nemo
    code-cursor
    vesktop
    trash-cli
    
    tree
    vnstat
    fzf
    zoxide
    sesh
    fd
    fastfetch
    pfetch
    neofetch
    ripgrep
    
    bibata-cursors
    papirus-icon-theme
    gnome-themes-extra
    
    font-awesome
    material-design-icons
    nerd-fonts.fira-code
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
    
    slurp
    redshift
    xdg-desktop-portal-hyprland
    xdg-desktop-portal-gtk
    wireplumber
    syncthing
    woeusb-ng
    ntfs3g
    vim
    btop
    pciutils
    bluetuith
    ncdu
    bat
    lsd
    android-tools
    unrar
    stig
    nix-output-monitor
    nh
    timer
    tomato-c
    ffmpeg-full
    pandoc
    libreoffice-qt6-still
    unzip
    autofs5
    bluez
    libnotify
    acpi
    dwm
    polybar
    tint2
    xclip
    xsel
    maim
    slop
    hyprland
    hyprlock
    hyprpaper
    wofi
    wf-recorder
    feh
    sioyek
    element-desktop
    alsa-utils
    alsa-ucm-conf
    pipewire
    sof-firmware
    linux-firmware
    alsa-firmware
    firefox-wayland
    qutebrowser
    gum
    cmake
    gnumake
    gcc
    libtool
    libvterm
    jre17_minimal
    nixfmt-rfc-style
    python3
    isort
    shellcheck
    ispell
    kotlin
    ktlint
    anki
    aegisub
    mpc-cli
    ncmpcpp
    nicotine-plus
    obs-cli
    tenacity
    lutris
    sox
    
    pamixer
    networkmanager
    networkmanagerapplet
    bluez-tools
    blueman
    udiskie
    kdePackages.sddm
    libsForQt5.qt5.qtquickcontrols
    libsForQt5.qt5.qtquickcontrols2
    libsForQt5.qt5.qtgraphicaleffects
    waybar
    wlogout
    hyprpicker
    satty
    cliphist
    hyprsunset
    polkit_gnome
    xdg-user-dirs
    parallel
    jq
    imagemagick
    libsForQt5.qt5.qtimageformats
    ffmpegthumbnailer
    libsForQt5.kde-cli-tools
    noto-fonts-emoji
    libsForQt5.qt5ct
    qt6Packages.qt6ct
    libsForQt5.qtstyleplugin-kvantum
    libsForQt5.qt5.qtwayland
    qt6Packages.qtwayland
    libsForQt5.dolphin
    libsForQt5.ark
    nwg-displays
    eza
    zsh-powerlevel10k
    starship
    fish
    hypridle
  ];
}
